package cmd

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/dmotles/sprawl/internal/agent"
	"github.com/dmotles/sprawl/internal/claude"
	"github.com/dmotles/sprawl/internal/memory"
	"github.com/dmotles/sprawl/internal/state"
	"github.com/dmotles/sprawl/internal/tmux"
	"github.com/spf13/cobra"
)

// ExitCodeShutdown is the exit code used to signal that the bash restart loop
// should stop and not restart the session. The bash loop generated by
// `sprawl init` checks for this code and breaks.
const ExitCodeShutdown = 42

// errShutdownRequested is a sentinel error indicating that the root session
// should exit with ExitCodeShutdown, causing the bash restart loop to stop.
var errShutdownRequested = errors.New("shutdown requested")

// rootTools is the set of tools available to the root agent.
var rootTools = []string{
	"Bash", "Read", "Glob", "Grep", "WebSearch", "WebFetch",
	"Agent", "Task", "TaskOutput", "TaskStop", "ToolSearch",
	"Skill", "TodoWrite", "TaskCreate", "TaskUpdate", "TaskList", "TaskGet",
	"AskUserQuestion", "EnterPlanMode", "ExitPlanMode",
}

// rootLoopDeps holds all injectable dependencies for the _root-session command.
type rootLoopDeps struct {
	getenv                    func(string) string
	findClaude                func() (string, error)
	buildPrompt               func(agent.PromptConfig) string
	buildContextBlob          func(sprawlRoot, rootName string) (string, error)
	writeSystemPrompt         func(string, string, string) (string, error)
	writeLastSessionID        func(string, string) error
	readFile                  func(string) ([]byte, error)
	removeFile                func(string) error
	newUUID                   func() (string, error)
	runCommand                func(name string, args []string) error
	stdout                    io.Writer
	readLastSessionID         func(string) (string, error)
	hasSessionSummary         func(sprawlRoot, sessionID string) (bool, error)
	autoSummarize             func(ctx context.Context, sprawlRoot, cwd, homeDir, sessionID string, invoker memory.ClaudeInvoker) (bool, error)
	userHomeDir               func() (string, error)
	newCLIInvoker             func() memory.ClaudeInvoker
	consolidate               func(ctx context.Context, sprawlRoot string, invoker memory.ClaudeInvoker, cfg *memory.TimelineCompressionConfig, now func() time.Time) error
	updatePersistentKnowledge func(ctx context.Context, sprawlRoot string, invoker memory.ClaudeInvoker, cfg *memory.PersistentKnowledgeConfig, sessionSummary string, timelineBullets string) error
	listRecentSessions        func(sprawlRoot string, n int) ([]memory.Session, []string, error)
	readTimeline              func(sprawlRoot string) ([]memory.TimelineEntry, error)
}

// defaultRootLoopDeps wires real implementations.
func defaultRootLoopDeps() *rootLoopDeps {
	return &rootLoopDeps{
		getenv:      os.Getenv,
		findClaude:  func() (string, error) { return exec.LookPath("claude") },
		buildPrompt: agent.BuildRootPrompt,
		buildContextBlob: func(sprawlRoot, rootName string) (string, error) {
			return memory.BuildContextBlob(sprawlRoot, rootName)
		},
		writeSystemPrompt:  state.WriteSystemPrompt,
		writeLastSessionID: memory.WriteLastSessionID,
		readFile:           os.ReadFile,
		removeFile:         os.Remove,
		newUUID:            state.GenerateUUID,
		runCommand: func(name string, args []string) error {
			cmd := exec.Command(name, args...)
			cmd.Stdin = os.Stdin
			cmd.Stdout = os.Stdout
			cmd.Stderr = os.Stderr
			return cmd.Run()
		},
		stdout:                    os.Stdout,
		readLastSessionID:         memory.ReadLastSessionID,
		hasSessionSummary:         memory.HasSessionSummary,
		autoSummarize:             memory.AutoSummarize,
		userHomeDir:               os.UserHomeDir,
		newCLIInvoker:             func() memory.ClaudeInvoker { return memory.NewCLIInvoker() },
		consolidate:               memory.Consolidate,
		updatePersistentKnowledge: memory.UpdatePersistentKnowledge,
		listRecentSessions:        memory.ListRecentSessions,
		readTimeline:              memory.ReadTimeline,
	}
}

var rootSessionCmd = &cobra.Command{
	Use:    "_root-session",
	Short:  "Run a single root agent session (internal use)",
	Hidden: true,
	Args:   cobra.NoArgs,
	RunE: func(_ *cobra.Command, _ []string) error {
		deps := defaultRootLoopDeps()
		err := runRootSession(context.Background(), deps)
		if errors.Is(err, errShutdownRequested) {
			os.Exit(ExitCodeShutdown)
		}
		return err
	},
}

func init() {
	rootCmd.AddCommand(rootSessionCmd)
}

// runRootSession runs a single Claude session for the root agent. It is called
// by the bash restart loop generated by `sprawl init`. The function:
//
//  1. Detects missed handoff from a previous session and auto-summarizes if needed
//  2. Builds the context blob and system prompt
//  3. Generates a session ID
//  4. Launches Claude interactively (blocks until exit)
//  5. Handles post-session housekeeping (handoff signal, consolidation)
//
// Exit code contract (mapped by the caller):
//   - return nil      → exit 0: normal exit, bash loop restarts immediately
//   - return error    → exit 1: startup failure, bash loop retries with delay
//   - return errShutdownRequested → exit 42: bash loop exits cleanly
//
// Note: Claude exiting non-zero (exec.ExitError) is treated as a normal exit
// (returns nil / exit 0) so the bash loop restarts. Only true startup failures
// (e.g., binary not found, missing env vars) return an error.
func runRootSession(ctx context.Context, deps *rootLoopDeps) error {
	sprawlRoot := deps.getenv("SPRAWL_ROOT")
	if sprawlRoot == "" {
		return fmt.Errorf("SPRAWL_ROOT environment variable is not set")
	}

	namespace := deps.getenv("SPRAWL_NAMESPACE")
	rootName := tmux.DefaultRootName

	claudePath, err := deps.findClaude()
	if err != nil {
		return fmt.Errorf("finding claude binary: %w", err)
	}

	// 0. Detect missed handoff from previous session.
	prevSessionID, _ := deps.readLastSessionID(sprawlRoot)
	if prevSessionID != "" {
		// Check if a summary already exists (e.g., from a successful handoff).
		// If so, skip the entire missed-handoff path to avoid false positives.
		alreadySummarized, _ := deps.hasSessionSummary(sprawlRoot, prevSessionID)
		if alreadySummarized {
			// Clear stale last-session-id so we don't check again next session.
			_ = deps.writeLastSessionID(sprawlRoot, "")
		} else {
			homeDir, homeErr := deps.userHomeDir()
			if homeErr != nil {
				fmt.Fprintf(deps.stdout, "[root-loop] warning: could not determine home directory, skipping auto-summarize: %v\n", homeErr)
			} else {
				fmt.Fprintf(deps.stdout, "[root-loop] Detected missed handoff from previous session\n")
				sp := startSpinner(deps.stdout, "auto-summarizing...")
				summarized, sumErr := deps.autoSummarize(ctx, sprawlRoot, sprawlRoot, homeDir, prevSessionID, deps.newCLIInvoker())
				sp.stop()
				if sumErr != nil {
					fmt.Fprintf(deps.stdout, "[root-loop] warning: auto-summarize failed for %s: %v\n", prevSessionID, sumErr)
				} else if summarized {
					fmt.Fprintf(deps.stdout, "[root-loop] auto-summarized missed handoff for session %s\n", prevSessionID)
					runConsolidationPipeline(ctx, deps, sprawlRoot)
				}
			}
		}
	}

	// 1. Build context blob (best-effort).
	contextBlob, ctxErr := deps.buildContextBlob(sprawlRoot, rootName)
	if ctxErr != nil {
		fmt.Fprintf(deps.stdout, "[root-loop] warning: context blob partial or failed: %v\n", ctxErr)
	}

	// 2. Build system prompt.
	systemPrompt := deps.buildPrompt(agent.PromptConfig{
		RootName:    rootName,
		AgentCLI:    "claude-code",
		ContextBlob: contextBlob,
		TestMode:    deps.getenv("SPRAWL_TEST_MODE") == "1",
	})
	promptPath, err := deps.writeSystemPrompt(sprawlRoot, rootName, systemPrompt)
	if err != nil {
		return fmt.Errorf("writing system prompt: %w", err)
	}

	// 3. Generate session ID.
	sessionID, err := deps.newUUID()
	if err != nil {
		return fmt.Errorf("generating session ID: %w", err)
	}
	if err := deps.writeLastSessionID(sprawlRoot, sessionID); err != nil {
		return fmt.Errorf("writing session ID: %w", err)
	}

	// 4. Build claude args (interactive mode).
	sessionName := tmux.RootSessionName(namespace, rootName)
	opts := claude.LaunchOpts{
		SystemPromptFile: promptPath,
		Tools:            rootTools,
		AllowedTools:     rootTools,
		DisallowedTools:  []string{"Edit", "Write", "NotebookEdit"},
		Name:             sessionName,
		Model:            "opus[1m]",
		SessionID:        sessionID,
	}
	args := opts.BuildArgs()

	fmt.Fprintf(deps.stdout, "[root-loop] starting session %s\n", sessionID)

	// 5. Run claude interactively (blocks until exit).
	runErr := deps.runCommand(claudePath, args)

	if runErr != nil {
		var exitErr *exec.ExitError
		if errors.As(runErr, &exitErr) {
			// Claude ran but exited non-zero — treat as normal exit.
			fmt.Fprintf(deps.stdout, "[root-loop] claude exited with code %d\n", exitErr.ExitCode())
		} else {
			// Failed to start — report as error (exit 1).
			return fmt.Errorf("claude failed to start: %w", runErr)
		}
	}

	// 6. Housekeeping: check handoff signal.
	handoffPath := filepath.Join(sprawlRoot, ".sprawl", "memory", "handoff-signal")
	if _, readErr := deps.readFile(handoffPath); readErr == nil {
		_ = deps.removeFile(handoffPath)
		// Clear last-session-id so the next session doesn't false-positive on missed handoff.
		_ = deps.writeLastSessionID(sprawlRoot, "")
		fmt.Fprintf(deps.stdout, "[root-loop] handoff signal detected, restarting\n")

		runConsolidationPipeline(ctx, deps, sprawlRoot)
	} else {
		fmt.Fprintf(deps.stdout, "[root-loop] session ended, restarting\n")
	}

	return nil
}

// runConsolidationPipeline runs timeline consolidation and persistent knowledge
// update. Both steps are best-effort: failures are logged as warnings.
func runConsolidationPipeline(ctx context.Context, deps *rootLoopDeps, sprawlRoot string) {
	sp := startSpinner(deps.stdout, "consolidating timeline...")
	cErr := deps.consolidate(ctx, sprawlRoot, deps.newCLIInvoker(), nil, nil)
	sp.stop()
	if cErr != nil {
		fmt.Fprintf(deps.stdout, "[root-loop] warning: consolidation failed: %v\n", cErr)
	}

	var sessionSummary string
	if sessions, bodies, err := deps.listRecentSessions(sprawlRoot, 1); err != nil {
		fmt.Fprintf(deps.stdout, "[root-loop] warning: reading latest session for persistent knowledge: %v\n", err)
	} else if len(sessions) > 0 && len(bodies) > 0 {
		sessionSummary = bodies[0]
	}

	var timelineBullets string
	if entries, err := deps.readTimeline(sprawlRoot); err != nil {
		fmt.Fprintf(deps.stdout, "[root-loop] warning: reading timeline for persistent knowledge: %v\n", err)
	} else {
		var tlb strings.Builder
		for _, e := range entries {
			fmt.Fprintf(&tlb, "- %s: %s\n", e.Timestamp.UTC().Format(time.RFC3339), e.Summary)
		}
		timelineBullets = tlb.String()
	}

	sp = startSpinner(deps.stdout, "updating persistent knowledge...")
	pkErr := deps.updatePersistentKnowledge(ctx, sprawlRoot, deps.newCLIInvoker(), nil, sessionSummary, timelineBullets)
	sp.stop()
	if pkErr != nil {
		fmt.Fprintf(deps.stdout, "[root-loop] warning: persistent knowledge update failed: %v\n", pkErr)
	}
}

// spinner displays an animated progress indicator on a single terminal line.
type spinner struct {
	w     io.Writer
	label string
	done  chan struct{}
	wg    sync.WaitGroup
}

// startSpinner starts a background goroutine that animates the spinner.
func startSpinner(w io.Writer, label string) *spinner {
	s := &spinner{
		w:     w,
		label: label,
		done:  make(chan struct{}),
	}
	s.wg.Add(1)
	go s.run()
	return s
}

// stop halts the spinner and clears the line. Blocks until cleanup is done.
func (s *spinner) stop() {
	close(s.done)
	s.wg.Wait()
}

func (s *spinner) run() {
	defer s.wg.Done()
	frames := []rune{'⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏'}
	start := time.Now()
	tick := time.NewTicker(150 * time.Millisecond)
	defer tick.Stop()
	i := 0
	for {
		select {
		case <-s.done:
			fmt.Fprintf(s.w, "\033[2K\r")
			return
		case <-tick.C:
			elapsed := time.Since(start).Truncate(time.Second)
			fmt.Fprintf(s.w, "\033[2K\r[root-loop]   %c %s (%s)", frames[i%len(frames)], s.label, elapsed)
			i++
		}
	}
}
