package cmd

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"

	"github.com/dmotles/sprawl/internal/claude"
	"github.com/dmotles/sprawl/internal/rootinit"
	"github.com/dmotles/sprawl/internal/tmux"
	"github.com/spf13/cobra"
)

// ExitCodeShutdown is the exit code used to signal that the bash restart loop
// should stop and not restart the session. The bash loop generated by
// `sprawl init` checks for this code and breaks.
const ExitCodeShutdown = 42

// errShutdownRequested is a sentinel error indicating that the root session
// should exit with ExitCodeShutdown, causing the bash restart loop to stop.
var errShutdownRequested = errors.New("shutdown requested")

// rootLoopDeps holds the injectable dependencies for the _root-session
// command that are specific to the tmux launch path. The mode-agnostic
// Phase A / Phase D work lives in internal/rootinit.
type rootLoopDeps struct {
	getenv     func(string) string
	findClaude func() (string, error)
	runCommand func(name string, args []string) error
	stdout     io.Writer
	rootinit   *rootinit.Deps
}

// defaultRootLoopDeps wires real implementations.
func defaultRootLoopDeps() *rootLoopDeps {
	return &rootLoopDeps{
		getenv:     os.Getenv,
		findClaude: func() (string, error) { return exec.LookPath("claude") },
		runCommand: func(name string, args []string) error {
			cmd := exec.Command(name, args...)
			cmd.Stdin = os.Stdin
			cmd.Stdout = os.Stdout
			cmd.Stderr = os.Stderr
			return cmd.Run()
		},
		stdout:   os.Stdout,
		rootinit: rootinit.DefaultDeps(),
	}
}

var rootSessionCmd = &cobra.Command{
	Use:    "_root-session",
	Short:  "Run a single root agent session (internal use)",
	Hidden: true,
	Args:   cobra.NoArgs,
	RunE: func(_ *cobra.Command, _ []string) error {
		deps := defaultRootLoopDeps()
		err := runRootSession(context.Background(), deps)
		if errors.Is(err, errShutdownRequested) {
			os.Exit(ExitCodeShutdown)
		}
		return err
	},
}

func init() {
	rootCmd.AddCommand(rootSessionCmd)
}

// runRootSession runs a single Claude session for the root agent. It is called
// by the bash restart loop generated by `sprawl init`. The function delegates
// the mode-agnostic pre-launch and post-launch housekeeping to
// internal/rootinit. Phase B (launch) is tmux-specific and lives here:
// interactive tty via exec.Command.
//
// Exit code contract (mapped by the caller):
//   - return nil      → exit 0: normal exit, bash loop restarts immediately
//   - return error    → exit 1: startup failure, bash loop retries with delay
//   - return errShutdownRequested → exit 42: bash loop exits cleanly
//
// Note: Claude exiting non-zero (exec.ExitError) is treated as a normal exit
// (returns nil / exit 0) so the bash loop restarts. Only true startup failures
// (e.g., binary not found, missing env vars) return an error.
func runRootSession(ctx context.Context, deps *rootLoopDeps) error {
	sprawlRoot := deps.getenv("SPRAWL_ROOT")
	if sprawlRoot == "" {
		return fmt.Errorf("SPRAWL_ROOT environment variable is not set")
	}

	namespace := deps.getenv("SPRAWL_NAMESPACE")
	rootName := tmux.DefaultRootName

	claudePath, err := deps.findClaude()
	if err != nil {
		return fmt.Errorf("finding claude binary: %w", err)
	}

	prepared, err := rootinit.Prepare(ctx, deps.rootinit, rootinit.ModeTmux, sprawlRoot, rootName, deps.stdout)
	if err != nil {
		return err
	}

	opts := claude.LaunchOpts{
		SystemPromptFile: prepared.PromptPath,
		Tools:            prepared.RootTools,
		AllowedTools:     prepared.RootTools,
		DisallowedTools:  prepared.Disallowed,
		Name:             namespace + rootName,
		Model:            prepared.Model,
		SessionID:        prepared.SessionID,
	}

	fmt.Fprintf(deps.stdout, "[root-loop] starting session %s\n", prepared.SessionID)

	runErr := deps.runCommand(claudePath, opts.BuildArgs())
	if runErr != nil {
		var exitErr *exec.ExitError
		if errors.As(runErr, &exitErr) {
			fmt.Fprintf(deps.stdout, "[root-loop] claude exited with code %d\n", exitErr.ExitCode())
		} else {
			return fmt.Errorf("claude failed to start: %w", runErr)
		}
	}

	return rootinit.FinalizeHandoff(ctx, deps.rootinit, sprawlRoot, deps.stdout)
}
