package cmd

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"time"

	"github.com/dmotles/sprawl/internal/claude"
	"github.com/dmotles/sprawl/internal/rootinit"
	"github.com/dmotles/sprawl/internal/tmux"
	"github.com/spf13/cobra"
)

// ExitCodeShutdown is the exit code used to signal that the bash restart loop
// should stop and not restart the session. The bash loop generated by
// `sprawl init` checks for this code and breaks.
const ExitCodeShutdown = 42

// resumeFailureWindow is the max runtime of a --resume invocation before we
// stop suspecting a resume-initialization failure. If claude exits within this
// window while Resume was requested, we fall back to a fresh session; if it
// ran longer, we assume the resume succeeded and later crashed mid-session
// (which is the normal bash-loop-restart case, not a retry).
const resumeFailureWindow = 5 * time.Second

// errShutdownRequested is a sentinel error indicating that the root session
// should exit with ExitCodeShutdown, causing the bash restart loop to stop.
var errShutdownRequested = errors.New("shutdown requested")

// rootLoopDeps holds the injectable dependencies for the _root-session
// command that are specific to the tmux launch path. The mode-agnostic
// Phase A / Phase D work lives in internal/rootinit.
type rootLoopDeps struct {
	getenv      func(string) string
	findClaude  func() (string, error)
	runCommand  func(name string, args []string) error
	now         func() time.Time
	stdout      io.Writer
	rootinit    *rootinit.Deps
	acquireLock func(sprawlRoot string) (weaveLockReleaser, error)
}

// weaveLockReleaser is the minimal interface the rootloop needs from an
// acquired lock — just Release(). Abstracting this lets tests stub the
// acquire call without touching the real filesystem.
type weaveLockReleaser interface {
	Release() error
}

// defaultRootLoopDeps wires real implementations.
func defaultRootLoopDeps() *rootLoopDeps {
	return &rootLoopDeps{
		getenv:     os.Getenv,
		findClaude: func() (string, error) { return exec.LookPath("claude") },
		runCommand: func(name string, args []string) error {
			cmd := exec.Command(name, args...)
			cmd.Stdin = os.Stdin
			cmd.Stdout = os.Stdout
			cmd.Stderr = os.Stderr
			return cmd.Run()
		},
		now:      time.Now,
		stdout:   os.Stdout,
		rootinit: rootinit.DefaultDeps(),
		acquireLock: func(sprawlRoot string) (weaveLockReleaser, error) {
			return rootinit.AcquireWeaveLock(sprawlRoot)
		},
	}
}

var rootSessionCmd = &cobra.Command{
	Use:    "_root-session",
	Short:  "Run a single root agent session (internal use)",
	Hidden: true,
	Args:   cobra.NoArgs,
	RunE: func(_ *cobra.Command, _ []string) error {
		deps := defaultRootLoopDeps()
		err := runRootSession(context.Background(), deps)
		if errors.Is(err, errShutdownRequested) {
			os.Exit(ExitCodeShutdown)
		}
		return err
	},
}

func init() {
	rootCmd.AddCommand(rootSessionCmd)
}

// runRootSession runs a single Claude session for the root agent. It is called
// by the bash restart loop generated by `sprawl init`. The function delegates
// the mode-agnostic pre-launch and post-launch housekeeping to
// internal/rootinit. Phase B (launch) is tmux-specific and lives here:
// interactive tty via exec.Command.
//
// Exit code contract (mapped by the caller):
//   - return nil      → exit 0: normal exit, bash loop restarts immediately
//   - return error    → exit 1: startup failure, bash loop retries with delay
//   - return errShutdownRequested → exit 42: bash loop exits cleanly
//
// Note: Claude exiting non-zero (exec.ExitError) is treated as a normal exit
// (returns nil / exit 0) so the bash loop restarts. Only true startup failures
// (e.g., binary not found, missing env vars) return an error.
//
// Resume-failure fallback: if rootinit.Prepare returns a resume-mode session
// and the claude process exits with an error within resumeFailureWindow, we
// assume `--resume` failed at init (e.g., server evicted the transcript) and
// retry once with rootinit.PrepareFresh. This cannot distinguish a genuine
// resume failure from a very fast crash, so the time window is the pragmatic
// heuristic.
func runRootSession(ctx context.Context, deps *rootLoopDeps) error {
	sprawlRoot := deps.getenv("SPRAWL_ROOT")
	if sprawlRoot == "" {
		return fmt.Errorf("SPRAWL_ROOT environment variable is not set")
	}

	namespace := deps.getenv("SPRAWL_NAMESPACE")
	rootName := tmux.DefaultRootName

	// Single-weave invariant: acquire the flock before doing any init work.
	// Released on return so the bash loop can re-acquire on the next
	// iteration (which is always sequential — the loop waits for us to
	// exit). The kernel drops the flock if this process is killed.
	lock, err := deps.acquireLock(sprawlRoot)
	if err != nil {
		printWeaveLockError(deps.stdout, err, namespace, sprawlRoot)
		return err
	}
	defer func() { _ = lock.Release() }()

	claudePath, err := deps.findClaude()
	if err != nil {
		return fmt.Errorf("finding claude binary: %w", err)
	}

	prepared, err := rootinit.Prepare(ctx, deps.rootinit, rootinit.ModeTmux, sprawlRoot, rootName, deps.stdout)
	if err != nil {
		return err
	}

	elapsed, runErr := launchClaude(deps, claudePath, namespace, rootName, prepared)

	// Resume-failure retry: if we asked claude to --resume and it died within
	// the detection window, fall back to a fresh session. Only retry once.
	// Beyond the window we assume resume succeeded and the exit was a genuine
	// mid-session termination (normal bash-loop-restart case).
	if runErr != nil && prepared.Resume && elapsed < resumeFailureWindow {
		fmt.Fprintf(deps.stdout, "[root-loop] resume failed for %s: %v — falling back to fresh session\n", prepared.SessionID, runErr)
		freshPrepared, freshErr := rootinit.PrepareFresh(ctx, deps.rootinit, rootinit.ModeTmux, sprawlRoot, rootName, deps.stdout)
		if freshErr != nil {
			return freshErr
		}
		_, runErr = launchClaude(deps, claudePath, namespace, rootName, freshPrepared)
	}

	if runErr != nil {
		var exitErr *exec.ExitError
		if errors.As(runErr, &exitErr) {
			fmt.Fprintf(deps.stdout, "[root-loop] claude exited with code %d\n", exitErr.ExitCode())
		} else {
			return fmt.Errorf("claude failed to start: %w", runErr)
		}
	}

	return rootinit.FinalizeHandoff(ctx, deps.rootinit, sprawlRoot, deps.stdout)
}

// launchClaude builds LaunchOpts from the prepared session and invokes the
// claude binary via deps.runCommand. It returns (runErr, elapsed) so the
// caller can decide whether a fast exit on a resume attempt warrants a
// fresh-session retry.
//
// If prepared.Resume is true, `--resume` is used and `--system-prompt-file` /
// `--session-id` are intentionally omitted (LaunchOpts.BuildArgs enforces
// this).
func launchClaude(deps *rootLoopDeps, claudePath, namespace, rootName string, prepared *rootinit.PreparedSession) (time.Duration, error) {
	opts := claude.LaunchOpts{
		Tools:           prepared.RootTools,
		AllowedTools:    prepared.RootTools,
		DisallowedTools: prepared.Disallowed,
		Name:            namespace + rootName,
		Model:           prepared.Model,
		SessionID:       prepared.SessionID,
	}
	if prepared.Resume {
		opts.Resume = true
		fmt.Fprintf(deps.stdout, "[root-loop] starting session %s (resume)\n", prepared.SessionID)
	} else {
		opts.SystemPromptFile = prepared.PromptPath
		fmt.Fprintf(deps.stdout, "[root-loop] starting session %s\n", prepared.SessionID)
	}

	start := deps.now()
	runErr := deps.runCommand(claudePath, opts.BuildArgs())
	return deps.now().Sub(start), runErr
}
